<h1>Try to get Iceland's mobility data</h1>

In [20]:
import requests
import pandas as pd
from matplotlib import pyplot as plt
from scipy.stats import gamma
import numpy as np

<h2>Helper methods for accessing the API</h2>

The helper methods in c3aidatalake.py convert a JSON response from the C3.ai APIs to a Pandas DataFrame. You may wish to view the code in c3aidatalake.py before using the quickstart examples.

In [21]:
import c3aidatalake as c3

In [22]:
location =  c3.fetch(
    "outbreaklocation",{"spec": {"filter" : "name != 'NaN' && locationType == 'country' && id == 'Poland'"
        }
    }
)
location

,latestTotalPopulation,populationOfAllChildren,locationType,populationCDS,countryArea,countryCode,population2018,population2019,id,name,typeIdent,hospitalPrediction.timestamp,location.value.id,location.timestamp,fips.id
0,32738308.0,32738308.0,country,38433600,304255.0,PL,37978548,37972812,Poland,PL,EP_LOC,2019-01-01T00:00:00,Poland,2020-08-09T00:00:00Z,PL

<h2>Lepiej używać countryCode według</h2>
<a href="https://en.wikipedia.org/wiki/List_of_FIPS_country_codes">kodów krajów FIPS</a>

In [25]:
location =  c3.fetch(
    "outbreaklocation",{"spec": {"filter" : "name != 'NaN' && locationType == 'country' && ( countryCode == 'PL' || countryCode == 'FI')"
        }
    }
)
location

,latestTotalPopulation,populationOfAllChildren,locationType,populationCDS,countryArea,countryCode,population2018,population2019,id,name,typeIdent,hospitalPrediction.timestamp,location.value.id,location.timestamp,fips.id
0,5475753.0,5475753.0,country,5516224,303815.0,FI,5518050,5517919,Finland,FI,EP_LOC,2019-01-01T00:00:00,Finland,2020-08-09T00:00:00Z,FI
1,32738308.0,32738308.0,country,38433600,304255.0,PL,37978548,37972812,Poland,PL,EP_LOC,2019-01-01T00:00:00,Poland,2020-08-09T00:00:00Z,PL

In [31]:
# Total number of confirmed cases, deaths, and recoveries in Santa Clara, California
today = pd.Timestamp.now().strftime("%Y-%m-%d")

casecounts = c3aidatalake.evalmetrics(
    "outbreaklocation",
    {
        "spec" : {
            "ids" : ["SantaClara_California_UnitedStates"],
            "expressions" : ["JHU_ConfirmedCases", "JHU_ConfirmedDeaths", "JHU_ConfirmedRecoveries"],
            "start" : "2020-01-01",
            "end" : today,
            "interval" : "DAY",
        }
    }
)

casecounts

,dates,SantaClara_California_UnitedStates.JHU_ConfirmedCases.data,SantaClara_California_UnitedStates.JHU_ConfirmedCases.missing,SantaClara_California_UnitedStates.JHU_ConfirmedDeaths.data,SantaClara_California_UnitedStates.JHU_ConfirmedDeaths.missing,SantaClara_California_UnitedStates.JHU_ConfirmedRecoveries.data,SantaClara_California_UnitedStates.JHU_ConfirmedRecoveries.missing
0,2020-01-01,0,0,0,0,0,100
0,2020-01-02,0,0,0,0,0,100
0,2020-01-03,0,0,0,0,0,100
0,2020-01-04,0,0,0,0,0,100
0,2020-01-05,0,0,0,0,0,100
...,...,...,...,...,...,...,...
0,2020-08-05,11030,0,192,0,0,0
0,2020-08-06,11336,0,196,0,0,0
0,2020-08-07,11336,0,196,0,0,0
0,2020-08-08,11475,0,203,0,0,0
0,2020-08-09,11687,0,204,0,0,0